import type { Channel } from "@/models/types/channel";
import type { VideoWithStats } from "@/models/types/video";
import type { TrendMetric } from "@/viewmodels/useTrends";

interface ReportData {
  channel: Channel;
  videos: VideoWithStats[];
  averageEngagement: number;
  topPerformers: VideoWithStats[];
  trendMetrics: TrendMetric[];
  engagementBreakdown: { name: string; views: number; likes: number; comments: number; engagementRate: number }[];
  dateRange: string;
}

function formatNumber(num: number): string {
  if (num >= 1_000_000_000) return `${(num / 1_000_000_000).toFixed(1)}B`;
  if (num >= 1_000_000) return `${(num / 1_000_000).toFixed(1)}M`;
  if (num >= 1_000) return `${(num / 1_000).toFixed(1)}K`;
  return num.toString();
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

export async function exportPDF(data: ReportData): Promise<void> {
  const { channel, videos, averageEngagement, topPerformers, trendMetrics } = data;
  
  const jsPDF = (await import("jspdf")).default;
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;
  let y = margin;
  let pageNumber = 1;

  let iconImageData: string | null = null;
  try {
    const response = await fetch("/icon.png");
    if (response.ok) {
      const buffer = await response.arrayBuffer();
      iconImageData = Buffer.from(buffer).toString("base64");
    }
  } catch {
    iconImageData = null;
  }

  const addHeader = () => {
    if (iconImageData) {
      pdf.addImage(iconImageData, "PNG", margin, 6, 12, 12);
    } else {
      pdf.setFillColor(79, 70, 229);
      pdf.rect(margin, 8, 4, 8, "F");
    }
    
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(14);
    pdf.setTextColor(17, 24, 39);
    pdf.text("VidMetrics Report", margin + 16, 14);
    
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(107, 114, 128);
    pdf.text(channel.title, pageWidth - margin, 12, { align: "right" });
    pdf.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), pageWidth - margin, 17, { align: "right" });
    
    pdf.setDrawColor(229, 231, 235);
    pdf.line(margin, 22, pageWidth - margin, 22);
  };

  const addFooter = () => {
    pdf.setDrawColor(229, 231, 235);
    pdf.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);
    
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(156, 163, 175);
    pdf.text("Generated by VidMetrics", margin, pageHeight - 7);
    pdf.text(`Page ${pageNumber}`, pageWidth - margin, pageHeight - 7, { align: "right" });
  };

  const checkPageBreak = (needed: number) => {
    if (y + needed > pageHeight - 20) {
      addFooter();
      pdf.addPage();
      pageNumber++;
      y = margin + 10;
      addHeader();
      return true;
    }
    return false;
  };

  const addSectionTitle = (title: string) => {
    checkPageBreak(12);
    pdf.setFillColor(249, 250, 251);
    pdf.rect(margin, y, contentWidth, 8, "F");
    
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(11);
    pdf.setTextColor(17, 24, 39);
    pdf.text(title, margin + 3, y + 5.5);
    
    pdf.setDrawColor(229, 231, 235);
    pdf.line(margin, y + 8, pageWidth - margin, y + 8);
    
    y += 14;
  };

  addHeader();
  y = 30;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(20);
  pdf.setTextColor(17, 24, 39);
  pdf.text("Channel Analytics Report", margin, y);
  y += 10;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.setTextColor(107, 114, 128);
  pdf.text(`${videos.length} videos analyzed`, margin, y);
  y += 12;

  addSectionTitle("Channel Overview");

  const stats = [
    { label: "Subscribers", value: formatNumber(channel.subscriberCount), color: [79, 70, 229] },
    { label: "Total Videos", value: formatNumber(channel.videoCount), color: [17, 24, 39] },
    { label: "Total Views", value: formatNumber(channel.viewCount), color: [5, 150, 105] },
    { label: "Avg Engagement", value: `${averageEngagement.toFixed(1)}%`, color: [17, 24, 39] },
  ];

  const cardWidth = (contentWidth - 9) / 4;
  stats.forEach((stat, i) => {
    const x = margin + i * (cardWidth + 3);
    checkPageBreak(22);
    
    pdf.setFillColor(249, 250, 251);
    pdf.setDrawColor(229, 231, 235);
    pdf.roundedRect(x, y, cardWidth, 18, 2, 2, "FD");
    
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(107, 114, 128);
    pdf.text(stat.label, x + cardWidth / 2, y + 6, { align: "center" });
    
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(14);
    pdf.setTextColor(stat.color[0], stat.color[1], stat.color[2]);
    pdf.text(stat.value, x + cardWidth / 2, y + 14, { align: "center" });
  });
  y += 24;

  addSectionTitle("Trend Analysis");

  const metricWidth = (contentWidth - 12) / 5;
  trendMetrics.forEach((metric, i) => {
    const x = margin + i * (metricWidth + 3);
    checkPageBreak(22);
    
    pdf.setFillColor(249, 250, 251);
    pdf.setDrawColor(229, 231, 235);
    pdf.roundedRect(x, y, metricWidth, 18, 2, 2, "FD");
    
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(7);
    pdf.setTextColor(107, 114, 128);
    pdf.text(metric.label.toUpperCase(), x + metricWidth / 2, y + 5, { align: "center" });
    
    let valueColor: [number, number, number] = [17, 24, 39];
    if (metric.trend?.isPositive) valueColor = [5, 150, 105];
    if (metric.trend?.isPositive === false) valueColor = [220, 38, 38];
    
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(12);
    pdf.setTextColor(valueColor[0], valueColor[1], valueColor[2]);
    pdf.text(metric.value, x + metricWidth / 2, y + 12, { align: "center" });
    
    if (metric.subValue) {
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(6);
      pdf.setTextColor(156, 163, 175);
      const subText = metric.subValue.length > 15 ? metric.subValue.slice(0, 15) + "..." : metric.subValue;
      pdf.text(subText, x + metricWidth / 2, y + 17, { align: "center" });
    }
  });
  y += 26;

  addSectionTitle("Top Performing Videos");

  const performerWidth = (contentWidth - 6) / 3;
  topPerformers.slice(0, 3).forEach((video, i) => {
    const x = margin + i * (performerWidth + 3);
    checkPageBreak(35);
    
    pdf.setFillColor(249, 250, 251);
    pdf.setDrawColor(229, 231, 235);
    pdf.roundedRect(x, y, performerWidth, 30, 2, 2, "FD");
    
    pdf.setFillColor(79, 70, 229);
    pdf.roundedRect(x + 3, y + 3, 8, 8, 1, 1, "F");
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(8);
    pdf.setTextColor(255, 255, 255);
    pdf.text(`#${i + 1}`, x + 7, y + 8.5, { align: "center" });
    
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(8);
    pdf.setTextColor(17, 24, 39);
    const title = video.title.length > 32 ? video.title.slice(0, 32) + "..." : video.title;
    pdf.text(title, x + 14, y + 8, { maxWidth: performerWidth - 18 });
    
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(7);
    pdf.setTextColor(107, 114, 128);
    pdf.text(formatDate(video.publishedAt), x + 14, y + 14);
    
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(9);
    pdf.setTextColor(79, 70, 229);
    pdf.text(formatNumber(video.viewCount), x + 4, y + 23);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(7);
    pdf.text("views", x + 4, y + 27);
    
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(9);
    pdf.setTextColor(5, 150, 105);
    pdf.text(formatNumber(video.likeCount), x + performerWidth / 2, y + 23, { align: "center" });
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(7);
    pdf.text("likes", x + performerWidth / 2, y + 27, { align: "center" });
    
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(9);
    pdf.setTextColor(220, 38, 38);
    pdf.text(`${video.engagementRate.toFixed(1)}%`, x + performerWidth - 4, y + 23, { align: "right" });
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(7);
    pdf.text("engagement", x + performerWidth - 4, y + 27, { align: "right" });
  });
  y += 36;

  addSectionTitle(`Video Performance (${Math.min(videos.length, 30)} videos)`);

  const colWidths = {
    title: 65,
    date: 25,
    views: 22,
    likes: 20,
    comments: 22,
    eng: 26
  };

  checkPageBreak(10);
  pdf.setFillColor(249, 250, 251);
  pdf.rect(margin, y, contentWidth, 7, "F");
  
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(8);
  pdf.setTextColor(107, 114, 128);
  
  let colX = margin + 2;
  pdf.text("TITLE", colX, y + 5);
  colX += colWidths.title;
  pdf.text("DATE", colX, y + 5);
  colX += colWidths.date;
  pdf.text("VIEWS", colX + colWidths.views - 12, y + 5);
  colX += colWidths.views;
  pdf.text("LIKES", colX + colWidths.likes - 14, y + 5);
  colX += colWidths.likes;
  pdf.text("COMMENTS", colX + colWidths.comments - 20, y + 5);
  colX += colWidths.comments;
  pdf.text("ENGAGEMENT", colX, y + 5);
  
  y += 7;
  pdf.setDrawColor(229, 231, 235);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 2;

  videos.slice(0, 30).forEach((video, index) => {
    checkPageBreak(9);
    
    if (index % 2 === 0) {
      pdf.setFillColor(250, 250, 250);
      pdf.rect(margin, y - 1, contentWidth, 7, "F");
    }
    
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(17, 24, 39);
    
    colX = margin + 2;
    const title = video.title.length > 40 ? video.title.slice(0, 40) + "..." : video.title;
    pdf.text(title, colX, y + 4.5, { maxWidth: colWidths.title - 4 });
    colX += colWidths.title;
    
    pdf.setTextColor(107, 114, 128);
    pdf.text(formatDate(video.publishedAt), colX, y + 4.5);
    colX += colWidths.date;
    
    pdf.setTextColor(17, 24, 39);
    pdf.text(formatNumber(video.viewCount), colX + colWidths.views - 12, y + 4.5);
    colX += colWidths.views;
    
    pdf.setTextColor(5, 150, 105);
    pdf.text(formatNumber(video.likeCount), colX + colWidths.likes - 14, y + 4.5);
    colX += colWidths.likes;
    
    pdf.setTextColor(220, 38, 38);
    pdf.text(formatNumber(video.commentCount), colX + colWidths.comments - 20, y + 4.5);
    colX += colWidths.comments;
    
    pdf.setTextColor(79, 70, 229);
    pdf.setFont("helvetica", "bold");
    pdf.text(`${video.engagementRate.toFixed(1)}%`, colX, y + 4.5);
    
    y += 7;
  });

  if (videos.length > 30) {
    checkPageBreak(8);
    pdf.setFont("helvetica", "italic");
    pdf.setFontSize(8);
    pdf.setTextColor(156, 163, 175);
    pdf.text(`Showing 30 of ${videos.length} videos`, margin + contentWidth / 2, y + 4, { align: "center" });
  }

  addFooter();

  pdf.save(`${channel.title.replace(/[^a-z0-9]/gi, "_")}_report_${new Date().toISOString().split("T")[0]}.pdf`);
}
